language: cpp
sudo: false
matrix:
  include:
    - compiler: gcc
      env: BUILDSYSTEM=makepanda PYTHONV=python2.7 FLAGS=--optimize=4
    - compiler: clang
      env: BUILDSYSTEM=makepanda PYTHONV=python3 FLAGS=--installer
    - compiler: clang
      env: BUILDSYSTEM=makepanda PYTHONV=python2.7 FLAGS=--override=STDFLOAT_DOUBLE=1
    - compiler: gcc
      dist: precise
      env: BUILDSYSTEM=cmake FLAGS=-DCOMPOSITE_SOURCE_LIMIT=0 # Disable unity builds to catch missing #include directives
    - compiler: clang
      dist: precise
      env: BUILDSYSTEM=cmake FLAGS=-DCOMPOSITE_SOURCE_LIMIT=0 # Disable unity builds to catch missing #include directives
    - compiler: gcc
      dist: trusty
      env: BUILDSYSTEM=cmake FLAGS=-DCOMPOSITE_SOURCE_LIMIT=0 # Disable unity builds to catch missing #include directives
    - compiler: clang
      dist: trusty
      env: BUILDSYSTEM=cmake FLAGS=-DCOMPOSITE_SOURCE_LIMIT=0 # Disable unity builds to catch missing #include directives
addons:
  apt:
    packages:
    - bison
    - flex
    - libfreetype6-dev
    - libgl1-mesa-dev
    - libjpeg-dev
    - libode-dev
    - libopenal-dev
    - libpng-dev
    - libssl-dev
    - libvorbis-dev
    - libx11-dev
    - libxcursor-dev
    - libxrandr-dev
    - nvidia-cg-toolkit
    - python-dev
    - python3-dev
    - zlib1g-dev
script:
- '[[ "$BUILDSYSTEM" != "makepanda" ]] || ( $PYTHONV makepanda/makepanda.py --everything --git-commit $TRAVIS_COMMIT $FLAGS --threads 4 && LD_LIBRARY_PATH=built/lib PYTHONPATH=built $PYTHONV makepanda/test_imports.py )'
- '[[ "$BUILDSYSTEM" != "cmake" ]] || ( mkdir build && cd build && mv ../makepanda/test_imports.py . && ../makepanda/selfdestruct.py --yes && cmake -DHAVE_GTK2=NO $FLAGS .. && make -j4 && python test_imports.py )'
notifications:
  irc:
    channels:
      - "chat.freenode.net#panda3d"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
